// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client"

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomepageDocumentDataSlicesSlice =
  | LogoSectionSlice
  | CarrouselSlice
  | HeroSlice
  | OnePhotoSectionSlice
  | BannerSlice
  | NewsSectionSlice
  | OffreSlice

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >

export type AllDocumentTypes = HomepageDocument

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * punchline field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: la punchline
   * - **API ID Path**: banner.default.primary.punchline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  punchline: prismic.KeyTextField

  /**
   * button text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: le texte du bouton
   * - **API ID Path**: banner.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * button link field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: le lien du bouton
   * - **API ID Path**: banner.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link: prismic.KeyTextField

  /**
   * button icon field in *Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: l'icone du bouton
   * - **API ID Path**: banner.default.primary.button_icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_icon: prismic.SelectField<"none" | "bell" | "hand" | "fork+knife">
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>

/**
 * Item in *Carrousel → Default → Primary → images*
 */
export interface CarrouselSliceDefaultPrimaryImagesItem {
  /**
   * image field in *Carrousel → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *Carrousel → Default → Primary*
 */
export interface CarrouselSliceDefaultPrimary {
  /**
   * title field in *Carrousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre de la section
   * - **API ID Path**: carrousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * images field in *Carrousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<CarrouselSliceDefaultPrimaryImagesItem>>
}

/**
 * Default variation for Carrousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarrouselSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Carrousel*
 */
type CarrouselSliceVariation = CarrouselSliceDefault

/**
 * Carrousel Shared Slice
 *
 * - **API ID**: `carrousel`
 * - **Description**: Carrousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrouselSlice = prismic.SharedSlice<
  "carrousel",
  CarrouselSliceVariation
>

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>

/**
 * Item in *LogoSection → Default → Primary → images*
 */
export interface LogoSectionSliceDefaultPrimaryImagesItem {
  /**
   * image field in *LogoSection → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *LogoSection → Default → Primary*
 */
export interface LogoSectionSliceDefaultPrimary {
  /**
   * title field in *LogoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: le titre de la section
   * - **API ID Path**: logo_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * images field in *LogoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<LogoSectionSliceDefaultPrimaryImagesItem>>
}

/**
 * Default variation for LogoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *LogoSection*
 */
type LogoSectionSliceVariation = LogoSectionSliceDefault

/**
 * LogoSection Shared Slice
 *
 * - **API ID**: `logo_section`
 * - **Description**: LogoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSectionSlice = prismic.SharedSlice<
  "logo_section",
  LogoSectionSliceVariation
>

/**
 * Item in *NewsSection → Default → Primary → body*
 */
export interface NewsSectionSliceDefaultPrimaryBodyItem {
  /**
   * image field in *NewsSection → Default → Primary → body*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_section.default.primary.body[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * title field in *NewsSection → Default → Primary → body*
   *
   * - **Field Type**: Text
   * - **Placeholder**: titre de l'actu
   * - **API ID Path**: news_section.default.primary.body[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * content field in *NewsSection → Default → Primary → body*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: contenu de l'actu
   * - **API ID Path**: news_section.default.primary.body[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * expiration date field in *NewsSection → Default → Primary → body*
   *
   * - **Field Type**: Date
   * - **Placeholder**: date d'expiration
   * - **API ID Path**: news_section.default.primary.body[].expiration_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  expiration_date: prismic.DateField
}

/**
 * Primary content in *NewsSection → Default → Primary*
 */
export interface NewsSectionSliceDefaultPrimary {
  /**
   * title field in *NewsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Actualités
   * - **API ID Path**: news_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * body field in *NewsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_section.default.primary.body[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  body: prismic.GroupField<Simplify<NewsSectionSliceDefaultPrimaryBodyItem>>
}

/**
 * Default variation for NewsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *NewsSection*
 */
type NewsSectionSliceVariation = NewsSectionSliceDefault

/**
 * NewsSection Shared Slice
 *
 * - **API ID**: `news_section`
 * - **Description**: NewsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSectionSlice = prismic.SharedSlice<
  "news_section",
  NewsSectionSliceVariation
>

/**
 * Item in *Offre → Default → Primary → detail*
 */
export interface OffreSliceDefaultPrimaryDetailItem {
  /**
   * subtitle field in *Offre → Default → Primary → detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: soutitre
   * - **API ID Path**: offre.default.primary.detail[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField

  /**
   * content field in *Offre → Default → Primary → detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: contenu de l'offre
   * - **API ID Path**: offre.default.primary.detail[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Primary content in *Offre → Default → Primary*
 */
export interface OffreSliceDefaultPrimary {
  /**
   * title field in *Offre → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: le titre de l'offre
   * - **API ID Path**: offre.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * detail field in *Offre → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre.default.primary.detail[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  detail: prismic.GroupField<Simplify<OffreSliceDefaultPrimaryDetailItem>>

  /**
   * image 1 field in *Offre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offre.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>

  /**
   * image2 field in *Offre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offre.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>

  /**
   * image3 field in *Offre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offre.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>

  /**
   * image4 field in *Offre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: offre.default.primary.image4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>

  /**
   * button text field in *Offre → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: text du bouton
   * - **API ID Path**: offre.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField

  /**
   * button icon field in *Offre → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: l'icone du bouton
   * - **API ID Path**: offre.default.primary.button_icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_icon: prismic.SelectField<"none" | "bell" | "hand" | "fork+knife">

  /**
   * button link field in *Offre → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: lien du bouton
   * - **API ID Path**: offre.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link: prismic.KeyTextField

  /**
   * title id field in *Offre → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: clé pour la navigation dans la page
   * - **API ID Path**: offre.default.primary.title_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_id: prismic.KeyTextField

  /**
   * reverse position field in *Offre → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: offre.default.primary.reverse_position
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse_position: prismic.BooleanField
}

/**
 * Default variation for Offre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OffreSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Offre*
 */
type OffreSliceVariation = OffreSliceDefault

/**
 * Offre Shared Slice
 *
 * - **API ID**: `offre`
 * - **Description**: Offre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OffreSlice = prismic.SharedSlice<"offre", OffreSliceVariation>

/**
 * Item in *OnePhotoSection → Default → Primary → icon and text*
 */
export interface OnePhotoSectionSliceDefaultPrimaryIconAndTextItem {
  /**
   * text field in *OnePhotoSection → Default → Primary → icon and text*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: le text à côté de l'icon
   * - **API ID Path**: one_photo_section.default.primary.icon_and_text[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * icon field in *OnePhotoSection → Default → Primary → icon and text*
   *
   * - **Field Type**: Select
   * - **Placeholder**: l'icone
   * - **API ID Path**: one_photo_section.default.primary.icon_and_text[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<"map" | "mail" | "phone" | "facebook" | "instagram">
}

/**
 * Primary content in *OnePhotoSection → Default → Primary*
 */
export interface OnePhotoSectionSliceDefaultPrimary {
  /**
   * image field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: one_photo_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * title field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Le titre de la section
   * - **API ID Path**: one_photo_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * content field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Le texte
   * - **API ID Path**: one_photo_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * icon and text field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: one_photo_section.default.primary.icon_and_text[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  icon_and_text: prismic.GroupField<
    Simplify<OnePhotoSectionSliceDefaultPrimaryIconAndTextItem>
  >

  /**
   * reverse position field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: one_photo_section.default.primary.reverse_position
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse_position: prismic.BooleanField

  /**
   * title_id field in *OnePhotoSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: le lien de navigation interne
   * - **API ID Path**: one_photo_section.default.primary.title_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_id: prismic.KeyTextField
}

/**
 * Default variation for OnePhotoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnePhotoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OnePhotoSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *OnePhotoSection*
 */
type OnePhotoSectionSliceVariation = OnePhotoSectionSliceDefault

/**
 * OnePhotoSection Shared Slice
 *
 * - **API ID**: `one_photo_section`
 * - **Description**: OnePhotoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OnePhotoSectionSlice = prismic.SharedSlice<
  "one_photo_section",
  OnePhotoSectionSliceVariation
>

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefault,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      CarrouselSlice,
      CarrouselSliceDefault,
      CarrouselSliceDefaultPrimary,
      CarrouselSliceDefaultPrimaryImagesItem,
      CarrouselSliceVariation,
      HeroSlice,
      HeroSliceDefault,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LogoSectionSlice,
      LogoSectionSliceDefault,
      LogoSectionSliceDefaultPrimary,
      LogoSectionSliceDefaultPrimaryImagesItem,
      LogoSectionSliceVariation,
      NewsSectionSlice,
      NewsSectionSliceDefault,
      NewsSectionSliceDefaultPrimary,
      NewsSectionSliceDefaultPrimaryBodyItem,
      NewsSectionSliceVariation,
      OffreSlice,
      OffreSliceDefault,
      OffreSliceDefaultPrimary,
      OffreSliceDefaultPrimaryDetailItem,
      OffreSliceVariation,
      OnePhotoSectionSlice,
      OnePhotoSectionSliceDefault,
      OnePhotoSectionSliceDefaultPrimary,
      OnePhotoSectionSliceDefaultPrimaryIconAndTextItem,
      OnePhotoSectionSliceVariation,
    }
  }
}
