// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  banner: dynamic(() => import("./Banner")),
  carrousel: dynamic(() => import("./Carrousel")),
  hero: dynamic(() => import("./Hero")),
  logo_section: dynamic(() => import("./LogoSection")),
  news_section: dynamic(() => import("./NewsSection")),
  offre: dynamic(() => import("./Offre")),
  one_photo_section: dynamic(() => import("./OnePhotoSection")),
}
